### ISSUE TITLE
Test data/ vignette data accessibility

### ISSUE THREAD

**Issue by dimurali93** [quadbiolab/Pando#15]
Hi, 

I would like to know if I could access the test data or the data used in the vignette to run the tutorial?

**Comment by joschif** [comment]
Hi @dimurali93, [here's a dropbox](https://www.dropbox.com/sh/hbihutdjd8agmht/AADExaEZn0lCAV1JVjpuOQtua?dl=0) with the example datasets used in the vignette. You should be able to run the tutorials with those. Let me know if anything is missing
