### ISSUE TITLE
phastCons for Mus musculus

### ISSUE THREAD

**Issue by sylestiel** [quadbiolab/Pando#27]
When working with mm10 genome what files do we download in lieu of the following:

data('phastConsElements20Mammals.UCSC.hg38')

**Comment by joschif** [comment]
You should be able to get the respective regions from the UCSC website https://genome.ucsc.edu/cgi-bin/hgTrackUi?db=mm9&g=cons30way

**Comment by Ping-lin14** [comment]
> 使用 mm10 基因組時，我們下載哪些文件來代替以下文件：
> 
> 數據（'phastConsElements20Mammals.UCSC.hg38'）

Hi,
Have you successfully created the mm10 replacement file?
Can you share it?

**Comment by sylestiel** [comment]
@Ping-lin14 @joschif @

Unfortunately, I have could not figured out how to download the appropriate mouse dataset.
