### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by Usamahussein551980** [quadbiolab/Pando#34]
I am working in a project of multiomic dataset generated from mouse, so I tried to apply Pando package on the data, but unfortunately I didn't go forward in the project. I stuck at the GRN inference, because the Pando used with a set of conserved regions "(phastConsElements20Mammals.UCSC.hg38) as well as predicted regulatory elements from [ENCODE](https://screen.encodeproject.org/) (SCREEN.ccRE.UCSC.hg38) for the human genome (hg38)".
I tried to download it from phastconn websites, but failed to go through any step.
Could you please help by providing another phastConservedElements for mm10 (mouse genome)?
Thank you

**Comment by joschif** [comment]
You can find conserved genomic regions for mouse genomes on the [UCSC genome browser website](https://genome.ucsc.edu/cgi-bin/hgTracks?db=mm10). However, you can also run Pando without it. Actually I would recommend to run it on linked peaks as outlined [here](https://quadbiolab.github.io/Pando/articles/regions.html). This should work independently of the genome.

**Comment by sylestiel** [comment]
@joschif 

The following approach
muo_data <- [initiate_grn](https://quadbiolab.github.io/Pando/reference/initiate_grn.html)(
    muo_data,
    rna_assay = 'RNA',
    peak_assay = 'peaks',
    regions = StringToGRanges(Links(muo_data[['peaks']])$peak)
)

Did not work for me either.

<img width="791" alt="Screen Shot 2023-03-09 at 9 49 59 AM" src="https://user-images.githubusercontent.com/64283689/224078267-d0dec10e-864d-4c00-82ea-57499320c3d2.png">

If you could suggest a workaround that would be helpful.

As far as the downloading the mouse genome from UCSC genome browser website. Could not figure out how to download it. I tried a few options but it was a no go.

Can you help with the exact code for mm10 and not mm9.

Much appreciated!
