### ISSUE TITLE
Question: Can Pando be used on an unpaired multiomic dataset?

### ISSUE THREAD

**Issue by mitchTwoTimes** [quadbiolab/Pando#35]
Is it possible to make a GRN using Pando on an integrated object like the one described [here](https://satijalab.org/seurat/articles/atacseq_integration_vignette.html)? 

Thank you

**Comment by joschif** [comment]
Pando can be used on any object that has both RNA and ATAC modalities for each sample/cell. If one integrates two datasets and summarizes them into metacells or high-resolution clusters, this should work. We have done something similar here: https://www.nature.com/articles/s41586-022-05279-8
