### ISSUE TITLE
infer_grn() parallelization cores not delivering results

### ISSUE THREAD

**Issue by stran94** [quadbiolab/Pando#37]
Whenever I run infer_grn() with parallel=TRUE, I get warning messages that some cores didn't return values. I also ran it without the parallelization and the grn results had a lot more connections. Anyone know how to prevent this issue with parallelization?

`Warning message:
In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  scheduled cores 3, 4, 5, 6, 7, 13, 14, 15, 18, 19, 20, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 49, 51, 52, 53, 54, 55, 56, 59, 60, 61, 62, 63, 64 did not deliver results, all values of the jobs will be affected
`

**Comment by joschif** [comment]
Hi @stran94, this seems to be an error caused by the `[parallel](https://www.rdocumentation.org/packages/parallel/versions/3.4.1)` package used for parallelization. Unfortunately I don't really know what the reason for this is or how to fix it, maybe you could approach the authors of that package.
