### ISSUE TITLE
initiate_grn error

### ISSUE THREAD

**Issue by zhijunyuu** [quadbiolab/Pando#40]
Hey Pando group,

Thanks for the very nice tool!
I was following the Vignette Basic workflow with the downloaded `muo_data`,
when I run the step `initiate_grn`, I got error as below:
`````
Error in validObject(object = .Object): invalid class "Seurat" object: 'assays' must be a named list
Traceback:

1. initiate_grn(muo_data, rna_assay = "RNA", peak_assay = "peaks", 
 .     regions = phastConsElements20Mammals.UCSC.hg38)
2. initiate_grn.Seurat(muo_data, rna_assay = "RNA", peak_assay = "peaks", 
 .     regions = phastConsElements20Mammals.UCSC.hg38)
3. as(object, "SeuratPlus")
4. asMethod(object)
5. new("SeuratPlus")
6. initialize(value, ...)
7. initialize(value, ...)
8. .local(.Object, ...)
9. validObject(object = .Object)
10. anyStrings(validityMethod(as(object, superClass)))
11. isTRUE(x)
12. validityMethod(as(object, superClass))
13. slot(object = object, name = "meta.data")
14. as(object, superClass)
15. asMethod(object)
16. new("Seurat")
17. initialize(value, ...)
18. initialize(value, ...)
19. .local(.Object, ...)
20. validObject(object = .Object)
21. stop(msg, ": ", errors, domain = NA)
`````

I have `Seurat_4.9.9.9048`, `Signac_1.9.0.9000` and `Pando_1.0.5` on R 4.2.2
Have you ever meet such error, do you maybe have any idea how to solve this error? 
Thanks in advance!

Best,
Zhijun

**Comment by joschif** [comment]
Hi @zhijunyuu, currently Pando does not yet support Seurat 5, and I think v4.9.9.9048 is effectively an early release version of v5, so to use Pando you would have to downgrade Seurat to a stable v4 release like 4.3.0. We'll try to add support for v5 in the future though. Cheers!

**Comment by joschif** [comment]
Hi everyone, I finally got around to updating Pando to be compatible with Seurat v5, which I believe should fix these issues. The new Pando version v1.1.0 is now incompatible with previous Seurat versions though.
