### ISSUE TITLE
cannot find some regions meta.features

### ISSUE THREAD

**Issue by zhenzuo2** [quadbiolab/Pando#6]
Hi,

I found some regions identified at `modules@meta` are not among `seurat_object@assays$peaks@meta.features`. 

For example, it is `chr15-89214422-89215304` in `modules@meta` but `chr15-89214422-89215059` in `seurat_object meta.features`.

Thank you!

**Comment by joschif** [comment]
Hi @zhenzuo2, depending on how you are selecting candidate regions, the regions used by Pando don't directly correspond to peaks. Have you used the `regions` argument in `initiate_grn()`? If so, the regions in Pando are an intersection of the peaks and those provided regions.

**Comment by joschif** [comment]
I'm closing this since there has not been any activity. Feel free to reopen it if the issue persists.

**Comment by zhenzuo2** [comment]
Thank you for your reply @joschif ! I found a few interesting TF-gene pairs and I want to plot peak counts for the candidate regions, gene expression, and TF expression. Is there any way I can extract those numbers from the fitted seurat_obejct? Thank you.
