### ISSUE TITLE
a subgraph of the GRN specifying only one "target gene"

### ISSUE THREAD

**Issue by m03077yhtnt** [quadbiolab/Pando#60]
Thank you so much for developing the wonderful package.
I understand that Pando can plot a subgraph of the GRN centered around one TF.
How about the opposite pattern?
I mean that does Pando have any function by which it can plot a subgraph of the GRN specifying only one "target gene"?
I would be happy if you could let me know it.

Yu

**Comment by joschif** [comment]
Hi @m03077yhtnt, currently this functionality is not implemented in Pando and you would have to do that manually. There's a chance you can trick Pando into thinking TFs are target genes by inverting the edges of the GRN graph and then using the TF-centered function, but I haven't tried that. If you wanted to implement it yourself, you probably would only have to lightly change the current Pando function. Best, Jonas
