### ISSUE TITLE
Question: where to find tutorial seurat object dataset

### ISSUE THREAD

**Issue by jennymoon90** [quadbiolab/Pando#61]
Hi,

Thank you for creating the Pando package. I'm trying to run the Vignettes (https://quadbio.github.io/Pando/articles/getting_started.html). I have installed the latest version of Pando 1.1.1, but I don't find the seurat object 'muo_data.rds' in the Vignette. I do notice that the Vignette is based on version 0.5.1. Would you kindly direct me to where I can download the necessary datasets for running through the Vignette?

Thanks,
Jenny

**Comment by elhaam** [comment]
They answered this question here: [https://github.com/quadbio/Pando/issues/47](https://github.com/quadbio/Pando/issues/47)
