### ISSUE TITLE
question of find_motifs

### ISSUE THREAD

**Issue by fengweimin-maker** [quadbiolab/Pando#68]
Hi author，

Thanks for the excellent software you have developed. It has been an invaluable tool in my research. However, I have encountered an issue while conducting an analysis on mouse data using the find_motifs function, and I am in need of your expertise to resolve it.
The error message I received is as follows:
![image](https://github.com/user-attachments/assets/c325882a-86a2-4d4c-8b46-ad417e8f87b1)
![image](https://github.com/user-attachments/assets/d1409660-b977-4b44-8d77-f0dfcdd2d668)

Does the motif_tf column of motif2tf have no motif-to-TF information? I have done human analysis before and there was no error at that time. I look forward to hearing from you soon.

Best,
Weimin

**Comment by joschif** [comment]
Hi @fengweimin-maker, the motif2tf dataframe that is provided by Pando is only meant for human, so for mouse you would need to provide a custom TF annotation.

**Comment by fengweimin-maker** [comment]
> motif2tf
Hi@joschif,
I am wondering if it is not too much trouble. I would be extremely grateful if you could share any scripts or code that could help us generate a motif2tf file specific to mice. Thanks!
