### ISSUE TITLE
Feature selection

### ISSUE THREAD

**Issue by zhenzuo2** [quadbiolab/Pando#9]
Hi,

Is FindVariableFeatures() needed before running pando? I am not sure which assay or matrix pando used for RNA seq data. Thank you.

**Comment by joschif** [comment]
Hi @zhenzuo2, if you run `FindVariableFeatures()` before running Pando, the default behavior is to only consider the selected features for GRN inference. However, you can directly choose the set of genes through the argument `genes` in `infer_grn()`.
Also, you can set the assays to be used with the `peak_assay` and `rna_assay` arguments to `initiate_grn()`. Within these assays Pando will always use the normalized data slot.
I hope this helps, cheers!

**Comment by joschif** [comment]
I'll close this now, but feel free to reopen if you have further questions
